CREATE TABLE VEICULO (
    id INT PRIMARY KEY IDENTITY (1, 1),
    nome VARCHAR (50) NOT NULL,
    valor FLOAT NOT NULL,
);

CREATE TABLE USUARIO (
    id INT PRIMARY KEY IDENTITY (1, 1),
    nome VARCHAR (50) NOT NULL,
    cpf DECIMAL (11) NOT NULL,
    sexo CHAR NOT NULL,
    nascimento DATE NOT NULL,
    idVeiculo INT NOT NULL,
    FOREIGN KEY (idVeiculo) REFERENCES VEICULO (id)
);

CREATE TABLE SEGURO (
	id INT PRIMARY KEY IDENTITY (1, 1),
	valorBase DECIMAL NOT NULL,
	idUsuario INT NOT NULL,
	FOREIGN KEY (idUsuario) REFERENCES USUARIO (id)
);